management:
   endpoint:
      health:
         show-components: always
      shutdown:
        enabled: true
   endpoints:
    web:
      exposure:
         include: "*"
   info:
      java:
         enabled: true
      os:
         enabled: true
      env:
         enabled: true
#   server:
#      port: 9876
info:
  app:
     name: hello-actuator
     company: yh

logging:
   level:
     hello.controller: debug
server:
   tomcat:
      mbeanregistry:
         enabled: true
